name: firebase_ui_auth
description: Pre-built widgets library that are integrated with the variety of the Firebase Auth providers.
version: 1.16.1
repository: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  email_validator: ^2.1.17
  dio: ^5.7.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_dynamic_links: ^6.1.0
  firebase_ui_localizations:
    git:
      url: https://github.com/waracle/FirebaseUI-Flutter
      path: packages/firebase_ui_localizations
  firebase_remote_config: ^5.1.5
  firebase_ui_oauth:
    git:
      url: https://github.com/waracle/FirebaseUI-Flutter
      path: packages/firebase_ui_oauth
  firebase_ui_shared:
    git:
      url: https://github.com/waracle/FirebaseUI-Flutter
      path: packages/firebase_ui_shared
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4

false_secrets:
  - example/**

flutter:
